{% set version = "4.0" %}
{% set build = 4 %}

package:
  name: mvapich
  version: {{ version }}

source:
  url: https://mvapich.cse.ohio-state.edu/download/mvapich/mv2/mvapich-{{ version }}.tar.gz
  sha256: c532f7bdd5cca71f78c12e0885c492f6e276e283711806c84d0b0f80bb3e3b74
  patches:
    - fix_ucr_domain.patch

build:
  number: {{ build }}
  string: h{{ PKG_HASH }}_{{ build }}
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_subpackage('mvapich', max_pin='x.y') }}

requirements:
  build:
    - bison
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - make
  host:
    - libhwloc
    - libfabric-devel <2.0
    - ucx
  run:
    - libnl
    - mpi 1.0.* mvapich
    - rdma-core

test:
  requires:
    - {{ compiler('c') }}

  commands:
{% if target_platform == "linux-64" %}
    - mpiexec -n 2 $PREFIX/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency -m 1024:1024
{% else %}
    - echo "Skipping linux-aarch64 & linux-ppc64le tests for now"
{% endif %}

about:
  home: https://mvapich.cse.ohio-state.edu/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYRIGHT
  summary: MVAPICH, a high-performance MPI library by The Ohio State University.
  description: |
    MVAPICH is a high-performance implementation of the MPI (Message Passing Interface) standard 
    with support for **both** Unified Communication X (UCX) and Open Fabric Interfaces (OFI).

    In case the actual *netmod* is not correctly recognized at run time, activate it using either
    `MPICH_CH4_NETMOD=ucx` or `MPICH_CH4_NETMOD=ofi`.

    ### About the Compilers
    Note that the actual GNU compilers (i.e., `gcc_linux-64`, `gfortran_linux-64` and `gxx_linux-64` for `linux-64`, or
    their equivalent for other platforms) have to be added manually since they are not automatically installed in the Conda
    environment as dependencies.

extra:
  recipe-maintainers:
    - j34ni
